---
# -*- coding: utf-8 -*-

before_script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - git submodule update --init
  - pip install --upgrade ansible ansible-lint
  - ansible --version
  - ansible-lint --version

stages:
  - ansible-lint
  - ansible-syntax-check

ansible-lint:
  stage: ansible-lint
  script:
    - ansible-lint systems.yaml

ansible-syntax-check:
  stage: ansible-syntax-check
  script:
    - ansible-playbook --inventory machines --syntax-check systems.yaml --extra-vars "type=server"