---
all:
  children:
    desktop:
      hosts:
        192.168.86.208
    docker:
      hosts:
        ubuntu:
          ansible_connection: docker
    laptop:
      hosts:
        192.168.86.232:
          host_key_checking: false
    # localhost:
    #   hosts:
    #     localhost:
    #       ansible_connection: local
    server:
      hosts:
        gkman.org:
          ansible_port: 2222
    virtualbox:
      hosts:
        gkman.org:
          ansible_port: 2222