---
- name: Docker Desktop
  hosts: docker_desktop
  remote_user: root
  become: true

  roles:
      - common
      - desktop
      - cleanup

- name: Docker Server
  hosts: docker_server
  remote_user: root
  become: true

  roles:
      - common
      - server
      - cleanup

- name: Laptop
  hosts: laptop
  remote_user: gkman
  become: true

  roles:
      - common
      - desktop
      - cleanup

- name: Localhost
  hosts: localhost
  remote_user: gkman
  become: true

  roles:
      - common
      - desktop
      - cleanup

- name: Server
  hosts: server
  remote_user: gkman
  become: true

  roles:
      - common
      - server
      - cleanup

- name: Virtualbox Desktop
  hosts: virtualbox_desktop
  remote_user: vmtest
  become: true

  roles:
      - common
      - desktop
      - cleanup

- name: Virtualbox Server
  hosts: virtualbox_server
  remote_user: vmtest
  become: true

  roles:
      - common
      - server
      - cleanup