---
- name: Docker
  hosts: docker
  remote_user: root
  become: true

  roles:
      - common
      - "{{ type }}"
      - cleanup

# - name: Laptop
#   hosts: laptop
#   remote_user: gkman
#   become: true

#   roles:
#       - setup
#       - "{{ type }}"
#       - cleanup

- name: Virtualbox
  hosts: virtualbox
  remote_user: vmtest
  become: true

  roles:
      - common
      - "{{ type }}"
      - cleanup
