---
- name: is dropbox installed
  command: dpkg-query --show dropbox
  register: dropbox_exists
  changed_when: False
  failed_when: False

- name: install dropbox
  apt:
    deb: https://linux.dropbox.com/packages/ubuntu/dropbox_2015.10.28_amd64.deb
  when: dropbox_exists.rc == 1

- name: download and unarchive IntelliJ
  unarchive:
    src: https://download-cf.jetbrains.com/idea/ideaIU-2017.3.4.tar.gz
    dest: /opt
    creates: /opt/idea-IU-173.4548.28
    remote_src: yes

- name: is slack installed
  command: dpkg-query --show slack-desktop
  register: slack_exists
  changed_when: False
  failed_when: False

- name: install slack
  apt:
    deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-2.5.2-amd64.deb
  when: slack_exists.rc == 1

- name: is steam installed
  command: dpkg-query --show steam-launcher
  register: steam_exists
  changed_when: False
  failed_when: False

- name: install steam
  apt:
    deb: https://steamcdn-a.akamaihd.net/client/installer/steam.deb
  when: steam_exists.rc == 1
