---
- name: is dropbox installed
  command: dpkg-query --show dropbox
  register: dropbox_exists
  changed_when: False
  failed_when: False

- name: install dropbox
  apt:
    deb: https://linux.dropbox.com/packages/ubuntu/dropbox_2015.10.28_amd64.deb
  when: dropbox_exists.rc == 1
