---
- name: "docker : install packages"
  apt:
    name:
    - ca-certificates
    - software-properties-common
    update_cache: yes

- name: "docker : add apt-key"
  apt_key:
    # id: 0EBFCD88
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present

- name: "docker : add Docker repository"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ release_codename }} stable
    state: present

- name: "docker : install Docker Community Edition"
  apt:
    name: docker-ce
    update_cache: yes
