---
- name: install packages
  apt: 
    name:
    - apt-transport-https
    - curl
    - gcc
    - git
    - htop
    - make
    - ncdu
    - net-tools
    - python
    - python3
    - python3-pip
    - python3-venv
    - ssh
    - tmux
    - tree
    - vim
    - wget
    - xclip
    - zsh
    update_cache: yes
