---
- name: install packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - curl
    - gcc
    - git
    - htop
    - make
    - ncdu
    - net-tools
    - python
    - python3.6
    - python3-pip
    - python3-venv
    - ssh
    - tmux
    - tree
    - vim
    - wget
    - xclip
    - zsh
