---
##
## Chrome setup
##
- name: "chrome : apt key"
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: "chrome : apt repository"
  apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present

##
## Skype setup
##
- name: "skype : apt key"
  apt_key:
    url: https://repo.skype.com/data/SKYPE-GPG-KEY
    state: present

- name: "skype : apt repository"
  apt_repository:
    repo: deb [arch=amd64] https://repo.skype.com/deb stable main
    state: present


- name: "steam : add multiverse"
  ansible.builtin.apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu/ {{ release_codename }} universe"

##
## VS Code setup
##
- name: "vscode : apt key"
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: "vscode : repository"
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: "vidcutter : repository"
  apt_repository:
    repo: ppa:ozmartian/apps

- name: "install app packages"
  apt:
    name:
    - ansible
    - code
    - google-chrome-stable
    - gradle
    - openjdk-8-jre
    - skypeforlinux
    - software-properties-common
    - sshpass
    # - steam
    - vidcutter
    - virtualbox
    # - virtualbox-ext-pack
    - vlc
    update_cache: yes

- name: "install snap packages"
  snap:
    name: slack
    classic: yes
