---
- name: Run "apt-get update"
  apt:
    update_cache: yes

- name: Install pre-req packages
  apt: name={{ item }}
  with_items:
    - curl
    - emacs
    - git
    - gradle
    - htop
    - ncdu
    - openjdk-8-jre
    - python
    - python3.6
    - ssh
    - tmux
    - vim
    - wget
    - zsh
