---
- name: Update repositories cache and install "apt-transport-https" package
  apt:
    name: apt-transport-https
    update_cache: yes
- name: Update repositories cache and install "ca-certificates" package
  apt:
    name: ca-certificates
    update_cache: yes
- name: Update repositories cache and install "software-properties-common" package
  apt:
    name: software-properties-common
    update_cache: yes
- name: Add Docker apt-key
  apt_key:
    id: 0EBFCD88
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present
- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable
    state: present
- name: Update repositories and install Docker Community Edition
  apt:
    name: docker-ce
    update_cache: yes